
##  Machine Learning em Produção 

## Persistindo Objetos em Disco ##

#### Importando as bibliotecas necessárias

In [1]:
import pickle
from sklearn.externals import joblib
import numpy as np
import _pickle as cPickle# vriação do pickle escrito em python C

C:\Users\Andre\Anaconda3\lib\site-packages\sklearn\externals\joblib\__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)


#### Criação do objeto do tipo lista.

In [2]:
lista = [1500,1234,567,14]

#### Criação do arquivo em disco.

In [3]:
arquivo = open('lista.pkl','wb') # w = escrita, b = binário

#### Persistindo o objeto em disco.

In [4]:
pickle.dump(lista,arquivo)

In [5]:
arquivo.close()

In [6]:
!ls

'ls' nÆo ‚ reconhecido como um comando interno
ou externo, um programa oper vel ou um arquivo em lotes.


#### Carregando o objeto a partir do disco para a memória.

In [7]:
arquivo2 = open('lista.pkl','rb')#r=read,b=binario

In [8]:
lista2 = pickle.load(arquivo2)

In [9]:
arquivo2.close()

In [10]:
lista2

[1500, 1234, 567, 14]

## Persistindo objetos utilizando o Numpy

#### Definindo o array

In [11]:
x = np.arange(10)#criando uma array com a faixa de valores até 10

In [12]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Persistindo o array em disco

In [13]:
np.save('array', x)#formato defaut é o npy, com n]ao foi indicado no nome do arquivo.

#### Listando os arquivos em disco

In [14]:
!ls

'ls' nÆo ‚ reconhecido como um comando interno
ou externo, um programa oper vel ou um arquivo em lotes.


#### Carregando o objeto a partir do disco para a memória.

In [15]:
x2 = np.load('array.npy')

In [16]:
x2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Persistindo a lista criada anteriormente em disco

In [17]:
np.save('lista2.npy',lista2)

#### Carregando o objeto a partir do disco para a memória.

In [18]:
lista3 = np.load('lista2.npy')

In [19]:
lista3

array([1500, 1234,  567,   14])

#### Verificando o tipo do objeto criado.

In [20]:
type(lista3)

numpy.ndarray

## Persistindo objetos utilizando o Joblib

#### Persistindo a lista criada anteriormente em disco.

In [21]:
joblib.dump(lista3,'lista3.joblib')

['lista3.joblib']

#### Listando os arquivos em disco

In [22]:
!ls

'ls' nÆo ‚ reconhecido como um comando interno
ou externo, um programa oper vel ou um arquivo em lotes.


#### Persistindo a lista criada anteriormente em disco utilizando compressão.

In [23]:
joblib.dump(lista3,'lista3.gz',compress=True)#Aqui o arquivo será comprimido

['lista3.gz']

#### Carregando o objeto a partir do disco para a memória.

In [24]:
lista4 = joblib.load('lista3.gz')

In [25]:
lista4

array([1500, 1234,  567,   14])